
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 14;
  public static final int LSQR = 24;
  public static final int LT = 10;
  public static final int OVER = 15;
  public static final int ELSE = 3;
  public static final int PLUS = 12;
  public static final int RPAREN = 17;
  public static final int INT = 4;
  public static final int SEMI = 18;
  public static final int WHILE = 7;
  public static final int RETURN = 5;
  public static final int ERROR = 30;
  public static final int IF = 2;
  public static final int EQLTY = 21;
  public static final int LPAREN = 16;
  public static final int GT = 11;
  public static final int ID = 28;
  public static final int NUM = 29;
  public static final int COMMA = 23;
  public static final int LTEQ = 19;
  public static final int RCRL = 27;
  public static final int EOF = 0;
  public static final int LCRL = 26;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int EQ = 9;
  public static final int GTEQ = 20;
  public static final int NTEQ = 22;
  public static final int VOID = 6;
  public static final int RSQR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LTEQ",
  "GTEQ",
  "EQLTY",
  "NTEQ",
  "COMMA",
  "LSQR",
  "RSQR",
  "LCRL",
  "RCRL",
  "ID",
  "NUM",
  "ERROR"
  };
}

